id: P007066
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6391
  title: ལམ་འབྲས་བསོད་དགའ་རིན་པོ་ཆེའི་རང་རྣམ།
  author: ''
  volumes:
    ba62d6f87728408ba30c29494de05a63:
      image_group_id: I3CN6393
      title: ''
      volume_number: 1
      total_pages: 540
ebook_metadata:
  title: ལམ་འབྲས་བསོད་དགའ་རིན་པོ་ཆེའི་རང་རྣམ།
  author: ''
  sku: P007066
  cover: cover.jpg
  layers:
  - pagination
